SELECT
	 	'Идентификатор: ' + GUID + ' | ' +
		'Открытие: ' + CONVERT(VARCHAR(20), CREATE_DATE, 120) + ' | ' +
		'Закрытие: ' + CONVERT(VARCHAR(20), OUT_TIME, 120) + ' | ' +
		'Продолжительность: ' +
	      CAST(DATEDIFF(SECOND, CREATE_DATE, OUT_TIME) / 86400 AS VARCHAR(32)) + 'д. ' +
		    CAST(DATEDIFF(SECOND, CREATE_DATE, OUT_TIME) / 3600 AS VARCHAR(32)) + 'ч. ' +
		    CAST(DATEDIFF(SECOND, CREATE_DATE, OUT_TIME) / 60 AS VARCHAR(32)) + 'мин. ' +
		    CAST(DATEDIFF(SECOND, CREATE_DATE, OUT_TIME) AS VARCHAR(32)) + 'сек.'
FROM BS_SESSION
WHERE (
		ISNULL(STATUS, 10) = 10
		AND DECRYPTBYKEY(USER_GUID) = '1A9A2317-D89B-4352-BBE6-8DA2B3C02836'
)