CREATE MASTER KEY ENCRYPTION BY PASSWORD = '927360'

CREATE ASYMMETRIC KEY bsAK
WITH ALGORITHM = RSA_2048
ENCRYPTION BY PASSWORD = '927360ab'

CREATE SYMMETRIC KEY bsSK
	WITH ALGORITHM = AES_256
	ENCRYPTION BY ASYMMETRIC KEY bsAK
